### PR TITLE
fix: onConfirm TypescriptRenameFile

### LINKED ISSUE #3: TypescriptRenameFile is not working
Hello, thanks for this great extension, really improves typescript development.
One of the main features I wanted was to rename files taking care to update the imports, something I really miss form vscode.
However,  I tried it and does nothing, it even asks for a new name, but then nothing happens.
Other commands like remove unused and short improts work properly, so I'm not sure what could happen with rename file. Is there any debug info I can get?

### PR DESCRIPTION
**Pull request by williamgoulois**
Hello ! 

First thank you for this plugin, i have been using null-ls for a year now as a typescript dev with LunarVim config.

This PR fixes #3 about TypescriptRenameFile.

The issue was about the tests for target and renameFile that are executed immediately after the input (and not only after confirmation). So the target was always undefined.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
I'm not sure this is the right fix - with these changes, exiting out of the prompt with `<C-c>`, entering a blank prompt, or entering the same path as the original file will print `Error executing Lua callback: Error`. 

After calling the command, its current behavior is this:

1. The user enters something invalid or exits the prompt. The command exist silently with no error.
2. The user enters a new path that doesn't already exist. No need for confirmation, so the command executes.
3. The user enters a path that already exists. If no `!` was used, the command prompts for confirmation, continues if the user hits `y`, and exits if the user hits `y`. If a `!` was used, the command proceeds without a prompt.

As far as I can tell, all of these cases are working as expected. Can you describe what exactly isn't working for you so we can come up with a fix?

**Comment by williamgoulois** [comment]
The behavior you specified is not the current one see this demo of the current problem. I printed the target value just to show you that this is executed before the user actually exited or confirmed the prompt and so the value is always `nil`

To match the expected behavior i changed the onConfirm to return instead of error. If the user uses <C-c>, <Esc>, "", or same as source it just returns silently.

Could you check and test the last commit ? It should be good now

**Comment by jose-elias-alvarez** [comment]
I think you might have forgotten to link the demo - I'd be curious to see it because the command is working OK for me. Either way, I like these changes and definitely feel that they make the code cleaner, so I'm happy to merge this.

**Comment by williamgoulois** [comment]
https://user-images.githubusercontent.com/37271970/169707529-54dae78e-73ca-47de-81fc-0b73294652fa.mov

You are right i forgot to link the demo !
This is on the main branch i just added this above the test of target
Screenshot 2022-05-22 at 19 23 26

**Comment by jose-elias-alvarez** [comment]
Very interesting - I think the issue might be that you are using a custom `vim.ui.input` handler. I can verify that this works with the default handler too, though, and the PR looks good. Thank you for the contribution!

**Comment by mmirus** [comment]
Awesome! I'll have to test this out this coming week. I've also been unable to get this to work. I'm using dressing and some other custom UI things, so that could be a factor if the suggestion above is correct. Thanks both!

**Pull request merged**
